/*
 * TennatApplication
 * An application to manage multi-tenancy information
 *
 * OpenAPI spec version: TennatApplication v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infa.products.tenant.client.rest.impl.auth;

import java.util.List;
import java.util.Map;

import com.infa.products.tenant.client.rest.impl.Pair;

public interface Authentication {
    /**
     * Apply authentication settings to header and query params.
     *
     * @param queryParams List of query parameters
     * @param headerParams Map of header parameters
     */
    void applyToParams(List<Pair> queryParams, Map<String, String> headerParams);
}
