/*
 * TennatApplication
 * An application to manage multi-tenancy information
 *
 * OpenAPI spec version: TennatApplication v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infa.products.tenant.client.rest.impl.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
